config/routes.rb
Rails.application.routes.draw do
  resources :expresses
  root 'welcome#index'
  
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    collection do
      get 'import'
      post 'import' => 'units#import'
    end
    resources :users, :controller => 'users'

    member do 
      # get 'index'
      get 'new_child_unit' => 'units#new'
      get 'child_units' => 'units#index'
      # get 'update_unit'
      # get 'destroy_unit'
    end
  end

  resources :users do
    member do
      get 'reset_pwd' => 'users#to_reset_pwd'
      patch 'reset_pwd' => 'users#reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/unit_users_controller.rb
class UnitUsersController < ApplicationController
  # before_action :find_unit, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  load_and_authorize_resource :unit
  load_and_authorize_resource :user, through: :unit, parent: false

  user_logs_filter only: [:create, :destroy], object: :user, symbol: :username
  #skip_load_resource :user, :only => :create

  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users_grid = initialize_grid(@users)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    respond_to do |format|
      if @user.save
        format.html { redirect_to unit_user_path(@unit,@user), notice: I18n.t('controller.create_success_notice', model: '用户') }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(unituser_params)
        format.html { redirect_to unit_user_path(@unit,@user), notice: I18n.t('controller.update_success_notice', model: '用户') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to unit_users_path(@unit) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_user
    #   @user = User.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def find_unit
    #   @unit = Unit.find(params[:unit_id])
    # end 
    
    def user_params
      params[:user].permit(:username, :name, :password, :email, :role)
    end 
end

app/views/unit_users/_form.html.erb
<%= form_for ([ @unit, @user]), :html => { :class => 'form-horizontal' } do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
    <% if can? :role, @user %>
    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <font color="red">(必填)</font>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field', :id => 'username' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <font color="red">(必填)</font>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field', :id => 'name' %>
      </div>
    </div>
  <% else %>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :username%></strong></dt>
      <font color="red">(必填)</font>
      <dd><%= @user.username %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :name%></strong></dt>
      <font color="red">(必填)</font>
      <dd><%= @user.name %></dd>
    </dl>
  <% end %>
  
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <font color="red">(必填)</font>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field', :id => 'password' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field', :id => 'email' %>
    </div>
  </div>

 <% if can? :role, @user %>
    <div class="control-group">
      <%= f.label :role, :class => 'control-label' %>
      <font color="red">(必选)</font>
      <div class="controls">
        <%= f.select(:role, User::ROLE.invert.select{|k, v| (can? :role, v.to_sym)}) %>
      </div>
    </div>
  <% else %>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :role%></strong></dt>
      <font color="red">(必选)</font>
      <dd><%= @user.rolename %></dd>
    </dl>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                unit_users_path(@unit), :class => 'btn' %>
  </div>
<% end %>

app/views/unit_users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/unit_users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human%></h1>
  <div style="float:right">
    <% if can? :new, User %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_unit_user_path(@unit),
                  :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<%= grid(@users_grid) do |g|

    g.column name: model_class.human_attribute_name(:name), attribute: 'name'

    g.column name: model_class.human_attribute_name(:username), attribute: 'username'

    g.column name: model_class.human_attribute_name(:email), attribute: 'email'

    g.column do |user|
      ActiveSupport::SafeBuffer.new << 
        (link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-xs btn-primary' if can? :update, user) << ' ' <<
          (link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' if can? :destroy, user)<< ' ' <<
          (link_to t('.reset_pwd', :default => t("helpers.links.reset_pwd")), to_reset_pwd_user_path(user), :class => 'btn btn-xs btn-primary' if can? :reset_pwd, user)<< ' ' <<
          (link_to user.is_unlocked? ? "用户停用" : "用户启用",  user.is_unlocked? ? lock_user_path(user) :  unlock_user_path(user), :class => 'btn btn-xs btn-primary', :method => :post, name: "switch_user_status", remote: true,  data: { type: 'json' } if can? :delete, user)
    end
  end 
%>

app/views/unit_users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/unit_users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_id) %>:</strong></dt>
  <dd><%= Unit.find(@user.unit_id).name %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              unit_users_path(@unit), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_user_path(@unit,@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_user_path(@unit,@user),
              :method => 'delete',
              :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>